name: flutter_bloc_login
description: Simple BLoC-handled login form

version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  authentication_repository:
    path: packages/authentication_repository
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  formz: ^0.6.0
  cupertino_icons: ^1.0.5
  user_repository:
    path: packages/user_repository

dev_dependencies:
  bloc_test: ^9.1.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
